baseurl: https://timmer.top
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: Timmerçš„å°æŠ„
copyright: Timmer

hasCJKLanguage: true

params:
  mainSections:
    - post
  
  featuredImageField: image

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    emoji: ğŸ¥
    subtitle: 1234567,7654321
    avatar:
      enabled: true
      local: true
      src: img/avatar.jpg

menu:
  main: []

  social:
    - identifier: github
      name: GitHub
      url: https://github.com/Timmer2338
      params:
        icon: brand-github